### PR TITLE
Development

### PR DESCRIPTION
**Pull request by gferrarocamus**
Project: SQL

### CODE REVIEW

**Comment by dipto0321** [comment]
Hi @gferrarocamus ,

Congratulation! All SQL passed.

- I found [this ](https://github.com/gferrarocamus/sql-zoo/blob/c24a1e760b22e02d6e8bd1892e5c38a61663c0bf/4%20SELECT%20within%20SELECT.sql#L57-L62) duplicate and Didn't find (9. Find the continents where all countries have a population <= 25000000. Then find the names of the countries associated with these continents. Show name, continent and population.)

- I found a wrong SQL [this](https://github.com/gferrarocamus/sql-zoo/blob/c24a1e760b22e02d6e8bd1892e5c38a61663c0bf/9%20Self%20join.sql#L1-L2) It should be removed. It should be like this `SELECT COUNT(*) FROM stops`

I think without those issues ☝️  everything is alright. After fixing those minor things you can merge into master. This is from me 👍 in advance.

Thanks 😸

**Comment by gferrarocamus** [comment]
Hi @dipto0321!

Thank you for the review. I can't seem to find the duplicate you mentioned above.

[Here](https://github.com/gferrarocamus/sql-zoo/blob/c24a1e760b22e02d6e8bd1892e5c38a61663c0bf/4%20SELECT%20within%20SELECT.sql#L57-L62), I see the query for question #9:

> Find the continents where all countries have a population <= 25000000. Then find the names of the countries associated with these continents. Show name, continent and population.

```
SELECT name, continent, population
FROM world x
WHERE 25000000 >= ALL(SELECT population
FROM world y
WHERE x.continent = y.continent)
GROUP BY continent,name, population
```

Is this not correct?

Thanks again for your input!

**Comment by dipto0321** [comment]
Hi @gferrarocamus ,

You are right. It was my fault. 😄 When I submit this on sqlzoo.net It was showing me the wrong answer and the last two SQL was quite similar. Maybe because of this my eye and brain confused. Anyway, Thanks for pointing it. For pointing this, A 🥇 from me 🙂

**Comment by gferrarocamus** [comment]
Awesome, @dipto0321! I'll go ahead with the merge then - thanks!

**Pull request merged**
